name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Ensure this directory path exists or is created
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Improves the analysis by disabling shallow clones
      - name: Set up msbuild
        uses: microsoft/setup-msbuild@v2
      - name: Install sonar-scanner and build-wrapper
        uses: sonarsource/sonarcloud-github-c-cpp@v3
      - name: Run build-wrapper
        run: |
          build-wrapper-win-x86-64 --out-dir "${{ env.BUILD_WRAPPER_OUT_DIR }}" msbuild sonar_scanner_example.vcxproj /t:rebuild /nodeReuse:false
      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner -D"sonar.cfamily.build-wrapper-output=${{ env.BUILD_WRAPPER_OUT_DIR }}"
